var searchData=
[
  ['safe_20register_20access_0',['Safe Register Access',['../index.html#autotoc_md28',1,'']]],
  ['safety_1',['Buffer Safety',['../architecture.html#autotoc_md100',1,'']]],
  ['security_20and_20robustness_20features_2',['Security and Robustness Features',['../architecture.html#security',1,'']]],
  ['sentinel_20collision_20risk_20in_20get_3',['⚠️ &lt;b&gt;Sentinel Collision Risk in get()&lt;/b&gt;',['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md68',1,'']]],
  ['sequence_20diagram_4',['Request-Response Sequence Diagram',['../architecture.html#sequence_diagram',1,'']]],
  ['serial_20communication_5',['Serial Communication',['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md75',1,'']]],
  ['serial0_6',['Arduino UNO (Serial0)',['../index.html#autotoc_md32',1,'']]],
  ['serial1_7',['Arduino MEGA (Serial1)',['../index.html#autotoc_md33',1,'']]],
  ['signaling_8',['✅ &lt;b&gt;IMPROVED: get() Not-Found Signaling&lt;/b&gt;',['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md65',1,'']]],
  ['silence_20window_9',['⚠️ &lt;b&gt;Frame Completion Depends on RTU Silence Window&lt;/b&gt;',['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md70',1,'']]],
  ['simplified_10',['Data Flow Diagram (Simplified)',['../index.html#autotoc_md9',1,'']]],
  ['slave_20⭐_20start_20here_11',['Level 1: Basic - Minimal Slave ⭐ START HERE',['../index.html#autotoc_md22',1,'']]],
  ['slave_20id_20matching_12',['Check 3: Slave ID Matching',['../architecture.html#autotoc_md95',1,'']]],
  ['special_20acknowledgment_13',['Special Acknowledgment',['../architecture.html#autotoc_md112',1,'']]],
  ['special_20thanks_14',['Special Thanks',['../index.html#autotoc_md47',1,'']]],
  ['start_15',['Quick Start',['../index.html#autotoc_md2',1,'']]],
  ['start_20here_16',['Level 1: Basic - Minimal Slave ⭐ START HERE',['../index.html#autotoc_md22',1,'']]],
  ['state_17',['Project State',['../index.html#autotoc_md13',1,'']]],
  ['state_20machine_20flowchart_18',['run() State Machine Flowchart',['../architecture.html#state_machine',1,'']]],
  ['static_20register_20pool_20mode_19',['✅ &lt;b&gt;ADDED: Optional Static Register Pool Mode&lt;/b&gt;',['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md57',1,'']]],
  ['steps_20',['Next Steps',['../index.html#autotoc_md38',1,'']]],
  ['stream_20transport_20support_21',['✅ &lt;b&gt;ADDED: Stream Transport Support&lt;/b&gt;',['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md64',1,'']]],
  ['string_22',['Level 3: Advanced - Typed Data (Float/Long/String)',['../index.html#autotoc_md24',1,'']]],
  ['structure_23',['Clean Project Structure',['../index.html#autotoc_md37',1,'']]],
  ['suggestions_24',['Future Enhancements (Suggestions)',['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md84',1,'']]],
  ['support_25',['Support',['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md72',1,'ℹ️ &lt;b&gt;No Modbus ASCII Support&lt;/b&gt;'],['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md63',1,'✅ &lt;b&gt;ADDED: FC15/FC16 Multi-Write Support&lt;/b&gt;'],['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md64',1,'✅ &lt;b&gt;ADDED: Stream Transport Support&lt;/b&gt;'],['../architecture.html#autotoc_md96',1,'Check 4: Function Code Support'],['../index.html#autotoc_md52',1,'Community Support']]],
  ['supported_20function_20codes_26',['Supported Function Codes',['../md__k_n_o_w_n___i_s_s_u_e_s.html#autotoc_md77',1,'']]],
  ['supported_20modbus_20function_20codes_27',['Supported Modbus Function Codes',['../index.html#autotoc_md14',1,'']]],
  ['system_20architecture_28',['System Architecture',['../index.html#autotoc_md7',1,'']]],
  ['system_20architecture_20and_20code_20flow_29',['System Architecture and Code Flow',['../architecture.html',1,'']]]
];
