Arduino Modbus RTU Slave: modbusSlave Class Reference
modbusSlave Class Reference
Core Runtime » Protocol Engine
Modbus RTU slave communications and frame processing engine.
#include <modbusSlave.h>
Public Member Functions
void calcCrc (void)
Calculate CRC for current frame buffer.
void checkSerial (void)
Legacy helper: check serial frame status.
void clearDiagnosticsCounters (void)
Reset all FC08 diagnostic counters to zero.
void configureEndianness (byte mode)
Set 32-bit helper endianness mode on bound register bank.
void diagnostics (word, word)
Handle FC08 diagnostics subfunctions.
void getAnalogStatus (byte, word, word)
Build analog status response payload.
word getBaud (void)
Get current configured baud rate.
word getBusCommunicationErrorCount (void)
Get FC08 bus communication error counter.
word getBusMessageCount (void)
Get FC08 bus message counter.
modbusDevice * getDevice (void)
Get currently bound device model pointer.
void getDigitalStatus (byte, word, word)
Build digital status response payload.
byte getEndianness (void)
Get active 32-bit helper endianness mode.
byte getProtocol (void)
Get active protocol framing mode.
word getSlaveMessageCount (void)
Get FC08 slave message counter.
modbusSlave (void)
Construct a slave instance with defaults.
bool onRead (word address, modbusReadCallback cb)
Register read callback for specific address.
bool onUnknownFunction (modbusUnknownFunctionCallback cb)
Register callback for unsupported/custom function codes.
bool onWrite (word address, modbusWriteCallback cb)
Register write callback for specific address.
void run (void)
Non-blocking slave engine tick.
void serialRx (void)
Legacy helper: receive serial payload.
void setBaud (word)
Configure RTU baud rate and frame timing.
void setDevice (modbusDevice *device)
Bind logical register device model.
void setPort (HardwareSerial &port)
Bind hardware serial transport.
void setPort (Stream &port)
Bind generic Stream transport.
void setProtocol (byte mode)
Select protocol transport framing mode (RTU default, optional ASCII).
void setStatus (byte, word, word)
Handle single-write function payloads.
void setStatusMultiple (byte, word, word)
Handle multi-write function payloads.
bool setStreamBaudHandler (modbusStreamBaudCallback cb)
Register baud reconfiguration callback for generic Stream transports.
void setTxEnableDelays (word preDelayMs, word postDelayMs)
Configure RS485 ms-level pre/post TX delays.
void setTxEnableDelaysUs (word preDelayUs, word postDelayUs)
Configure RS485 us-level pre/post TX delays.
void setTxEnablePin (byte pin, bool activeHigh=true)
Configure RS485 DE/RE direction pin control.
Detailed Description
Modbus RTU slave communications and frame processing engine.
Internal parser state machine used by run():
Definition at line 73 of file modbusSlave.h.
Constructor & Destructor Documentation
modbusSlave()
modbusSlave::modbusSlave (void)
Construct a slave instance with defaults.
Definition at line 86 of file modbusSlave.cpp.
References MODBUS_MAX_READ_CALLBACKS, MODBUS_MAX_WRITE_CALLBACKS, RTU, and SERIALBAUD.
Member Function Documentation
calcCrc()
void modbusSlave::calcCrc (void)
Calculate CRC for current frame buffer.
Definition at line 301 of file modbusSlave.cpp.
References _auchCRCHi, _auchCRCLo, and ASCII.
Referenced by diagnostics(), getAnalogStatus(), getDigitalStatus(), setStatus(), and setStatusMultiple().
checkSerial()
void modbusSlave::checkSerial (void)
Legacy helper: check serial frame status.
Definition at line 333 of file modbusSlave.cpp.
References MODBUS_MAX_FRAME.
clearDiagnosticsCounters()
void modbusSlave::clearDiagnosticsCounters (void)
Reset all FC08 diagnostic counters to zero.
Useful for periodic diagnostics reset or after maintenance.
Definition at line 264 of file modbusSlave.cpp.
configureEndianness()
void modbusSlave::configureEndianness (byte mode)
Set 32-bit helper endianness mode on bound register bank.
Definition at line 243 of file modbusSlave.cpp.
diagnostics()
void modbusSlave::diagnostics (word subFunction, word data)
Handle FC08 diagnostics subfunctions.
Definition at line 816 of file modbusSlave.cpp.
References calcCrc(), DIAG_BUS_COMM_ERROR_COUNT, DIAG_BUS_MESSAGE_COUNT, DIAG_RETURN_QUERY_DATA, DIAG_SLAVE_MESSAGE_COUNT, and DIAGNOSTICS.
getAnalogStatus()
void modbusSlave::getAnalogStatus (byte funcType, word startreg, word numregs)
Build analog status response payload.
Definition at line 694 of file modbusSlave.cpp.
References calcCrc(), MODBUS_MAX_FRAME, and READ_AI.
getBaud()
word modbusSlave::getBaud (void) inline
Get current configured baud rate.
Definition at line 130 of file modbusSlave.h.
getBusCommunicationErrorCount()
word modbusSlave::getBusCommunicationErrorCount (void)
Get FC08 bus communication error counter.
Definition at line 254 of file modbusSlave.cpp.
getBusMessageCount()
word modbusSlave::getBusMessageCount (void)
Get FC08 bus message counter.
Definition at line 249 of file modbusSlave.cpp.
getDevice()
modbusDevice * modbusSlave::getDevice (void) inline
Get currently bound device model pointer.
Definition at line 81 of file modbusSlave.h.
getDigitalStatus()
void modbusSlave::getDigitalStatus (byte funcType, word startreg, word numregs)
Build digital status response payload.
Definition at line 632 of file modbusSlave.cpp.
References calcCrc(), MODBUS_MAX_FRAME, and READ_DI.
getEndianness()
byte modbusSlave::getEndianness (void) inline
Get active 32-bit helper endianness mode.
Definition at line 111 of file modbusSlave.h.
References MODBUS_BIG_ENDIAN.
getProtocol()
byte modbusSlave::getProtocol (void) inline
Get active protocol framing mode.
Definition at line 128 of file modbusSlave.h.
getSlaveMessageCount()
word modbusSlave::getSlaveMessageCount (void)
Get FC08 slave message counter.
Definition at line 259 of file modbusSlave.cpp.
run()
void modbusSlave::run (void)
Non-blocking slave engine tick.
Call this continuously from Arduino loop().
Definition at line 1055 of file modbusSlave.cpp.
References ASCII, and MODBUS_MAX_FRAME.
serialRx()
void modbusSlave::serialRx (void)
Legacy helper: receive serial payload.
Definition at line 363 of file modbusSlave.cpp.
References MODBUS_MAX_FRAME.
setBaud()
void modbusSlave::setBaud (word baud)
Configure RTU baud rate and frame timing.
Definition at line 276 of file modbusSlave.cpp.
setDevice()
void modbusSlave::setDevice (modbusDevice * device)
Bind logical register device model.
Definition at line 131 of file modbusSlave.cpp.
setPort() [1/2]
void modbusSlave::setPort (HardwareSerial & port)
Bind hardware serial transport.
Definition at line 136 of file modbusSlave.cpp.
setPort() [2/2]
void modbusSlave::setPort (Stream & port)
Bind generic Stream transport.
Definition at line 142 of file modbusSlave.cpp.
setProtocol()
void modbusSlave::setProtocol (byte mode)
Select protocol transport framing mode (RTU default, optional ASCII).
Definition at line 148 of file modbusSlave.cpp.
References ASCII, and RTU.
setStatus()
void modbusSlave::setStatus (byte funcType, word reg, word val)
Handle single-write function payloads.
Definition at line 741 of file modbusSlave.cpp.
References calcCrc(), and WRITE_DO.
setStatusMultiple()
void modbusSlave::setStatusMultiple (byte funcType, word reg, word count)
Handle multi-write function payloads.
Definition at line 776 of file modbusSlave.cpp.
References calcCrc(), and WRITE_DO_MULTI.
The documentation for this class was generated from the following files:
modbusSlave.h
modbusSlave.cpp